# Generated by Django 2.1.1 on 2018-09-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='商品名称')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='df_goods', verbose_name='商品图片')),
                ('address', models.CharField(max_length=20, verbose_name='商品地址')),
                ('position', models.CharField(max_length=20, verbose_name='经纬度')),
                ('movie_name', models.CharField(max_length=20, verbose_name='电影名')),
                ('Cinema', models.CharField(max_length=20, verbose_name='电影院名')),
                ('seat', models.CharField(max_length=20, verbose_name='座位信息')),
                ('redeem_code', models.CharField(max_length=20, verbose_name='兑换码')),
                ('code_sms', models.CharField(max_length=500, verbose_name='买票短信')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='票价')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('startDate', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('endDate', models.DateTimeField(max_length=20, verbose_name='结束时间')),
                ('gclick', models.IntegerField(verbose_name='点击量')),
                ('state', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, verbose_name='类型名称')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android.TypeInfo', verbose_name='所属分类'),
        ),
    ]
